### ISSUE TITLE
Error when configuring the `eth2` package in the enclave manager

### ISSUE THREAD

**Issue by leoporoli** [kurtosis-tech/kurtosis#1383]
### What's your CLI version?

0.83.6

### Description & steps to reproduce

I went to `cloud.kurtosis.com` -> then `create new enclave` -> then I chose `eth2 package` -> then I pressed the "Configure>>" button and I get this error:

`TypeError: Cannot read properties of undefined (reading 'topLevelType')
    at https://cloud.kurtosis.com/gateway/ips/54-237-148-74/ports/9711/static/js/main.2a6e7beb.js:2:831831
    at Array.map (<anonymous>)
    at Tw (https://cloud.kurtosis.com/gateway/ips/54-237-148-74/ports/9711/static/js/main.2a6e7beb.js:2:831767)
    at Ow (https://cloud.kurtosis.com/gateway/ips/54-237-148-74/ports/9711/static/js/main.2a6e7beb.js:2:835847)
    at Ti (https://cloud.kurtosis.com/gateway/ips/54-237-148-74/ports/9711/static/js/main.2a6e7beb.js:2:153819)
    at Tu (https://cloud.kurtosis.com/gateway/ips/54-237-148-74/ports/9711/static/js/main.2a6e7beb.js:2:210932)
    at kl (https://cloud.kurtosis.com/gateway/ips/54-237-148-74/ports/9711/static/js/main.2a6e7beb.js:2:200038)
    at yl (https://cloud.kurtosis.com/gateway/ips/54-237-148-74/ports/9711/static/js/main.2a6e7beb.js:2:199966)
    at gl (https://cloud.kurtosis.com/gateway/ips/54-237-148-74/ports/9711/static/js/main.2a6e7beb.js:2:199829)
    at il (https://cloud.kurtosis.com/gateway/ips/54-237-148-74/ports/9711/static/js/main.2a6e7beb.js:2:196609)`
    
    
<img width="1355" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/29951623/c02f00b2-680c-4c78-834a-9c8d952a1067">

### Desired behavior

configure and run the `eth2-package` 

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by adschwartz** [comment]
@leoporoli I released a fix for this issue this morning. can you check if you still have this issue on the latest release `>= 0.83.8`.

**Comment by mieubrisse** [comment]
Same thing as #1384

**Comment by leoporoli** [comment]
@adschwartz it worked for me with the latest release, you can close this ticket

**Comment by adschwartz** [comment]
Closing
