### ISSUE TITLE
Kurtosis dump doesn't work after deploying to Kubernetes

### ISSUE THREAD

**Issue by MuhammedIrfan** [kurtosis-tech/kurtosis#2083]
### What's your CLI version?

0.86.11

### Description & steps to reproduce

After deploying to remote Kubernetes cluster when performing `kurtosis dump` from CLI it fails with below error.

```
INFO[2024-01-25T22:01:36+05:30] Engine running in Kubernetes cluster, to connect to the engine from outside the cluster run 'kurtosis gateway' to open a local gateway to the engine 
panic: implement me

goroutine 1 [running]:
github.com/kurtosis-tech/kurtosis/container-engine-lib/lib/backend_impls/kubernetes/kubernetes_kurtosis_backend.(*KubernetesKurtosisBackend).DumpKurtosis(0x1400079f9d8?, {0x1023401b0?, 0x140005468f0?}, {0x140004aa280?, 0x19?})
	/root/project/container-engine-lib/lib/backend_impls/kubernetes/kubernetes_kurtosis_backend/kubernetes_kurtosis_backend.go:53 +0x2c
github.com/kurtosis-tech/kurtosis/container-engine-lib/lib/backend_impls/metrics_reporting.(*MetricsReportingKurtosisBackend).DumpKurtosis(0x1024a109c?, {0x102dba9a0?, 0x140008d82a0?}, {0x1400005c820, 0x19})
	/root/project/container-engine-lib/lib/backend_impls/metrics_reporting/metrics_reporting_kurtosis_backend.go:110 +0x38
github.com/kurtosis-tech/kurtosis/cli/cli/commands/dump.run({0x102dba9a0, 0x140008d82a0}, {0x102dd0278, 0x14000512520}, {0xe?, 0x102d987b8?}, {0x102989a40?, 0x140004a36a0?}, 0x1024aeeac?, 0xe?)
	/root/project/cli/cli/commands/dump/dump.go:66 +0x168
github.com/kurtosis-tech/kurtosis/cli/cli/command_framework/highlevel/engine_consuming_kurtosis_command.(*EngineConsumingKurtosisCommand).getRunFunc.func1({0x102dba9a0, 0x140008d82a0}, 0x0?, 0x103d50eb8?)
	/root/project/cli/cli/command_framework/highlevel/engine_consuming_kurtosis_command/engine_consuming_kurtosis_command.go:246 +0x198
github.com/kurtosis-tech/kurtosis/cli/cli/command_framework/lowlevel.(*LowlevelKurtosisCommand).MustGetCobraCommand.func2(0x14000493b00?, {0x103d50eb8, 0x0, 0x0})
	/root/project/cli/cli/command_framework/lowlevel/lowlevel_kurtosis_command.go:301 +0x330
github.com/spf13/cobra.(*Command).execute(0x14000493b00, {0x103d50eb8, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x103cfc460)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/root/project/cli/cli/main.go:52 +0x80
```

### Desired behavior

Upon running `kurtosis dump` i should be able to dump container logs & configuration to my host machine

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by galenmarchetti** [comment]
thank you @MuhammedIrfan  and apologies for the delay in responding to this - we have some other folks using k8s `enclave dump` recently so I just wanted to check if this is still an issue for you? if so, will dig deeper into repro'ing it so we can get you a fix
