### ISSUE TITLE
Web UI doesn't load due to "Unexpected Application Error"

### ISSUE THREAD

**Issue by jimmygchen** [kurtosis-tech/kurtosis#2505]
### What's your CLI version?

0.90.1

### Description & steps to reproduce

The below occurs when I open the enclave manager with `kurtosis web`.

<img width="693" alt="image" src="https://github.com/kurtosis-tech/kurtosis/assets/742762/e0e97832-e7fb-4f7a-80b4-3073eedc205a">

Unfortunately I don't have the steps now to make this a useful bug report - sorry. However this issue still occur from time to time and to others as well. I'll make sure I get details when I see it again.

Looks like there's some enclave state that's not handled by the UI. The workaround now is to remove the enclave and restart the engine.

I think the bug is here (missing an `undefined` check):
https://github.com/kurtosis-tech/kurtosis/blob/36065a853db8a1bc76a852873aaa14949220ae59/enclave-manager/web/packages/app/src/emui/enclaves/components/tables/PortsTable.tsx#L62

I'd be happy to attempt a fix when I get some time in the next week or so, if no one gets to this.

### Desired behavior

The web UI should load correctly.

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

**Comment by jimmygchen** [comment]
I can't reproduce this with `ethereum-package` anymore. 
Is it a possible state to have private ports defined but not mapped to an external port?
Seems like it's either a bug in older version that's been fixed, or an invalid state that I got in somehow.

**Comment by siladu** [comment]
I am getting this with recent versions of kurtosis and ethereum-package

```
kurtosis version
CLI Version:   1.15.1
```

```
Unexpected Application Error!
Cannot read properties of undefined (reading 'number')
TypeError: Cannot read properties of undefined (reading 'number')
    at http://localhost:9711/static/js/main.c69d588b.js:2:2158848
    at Array.map (<anonymous>)
    at lle (http://localhost:9711/static/js/main.c69d588b.js:2:2158358)
    at http://localhost:9711/static/js/main.c69d588b.js:2:2182697
    at Array.flatMap (<anonymous>)
    at http://localhost:9711/static/js/main.c69d588b.js:2:2182685
    at http://localhost:9711/static/js/main.c69d588b.js:2:2182810
    at Array.map (<anonymous>)
    at qle (http://localhost:9711/static/js/main.c69d588b.js:2:2182226)
    at Ea (http://localhost:9711/static/js/main.c69d588b.js:2:296998)
```
