### ISSUE TITLE
Switching contexts throws a panic

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#597]
### What's your CLI version?

0.75.9

### Description & steps to reproduce

```
$ kurtosis context ls
 15:42:38 /Users/argos/Library/CloudStorage/GoogleDrive-thetallmonkey@gmail.com/My Drive/checklists-and-templates/brazil-apartment-bills (master)  kurtosis context ls
    UUID           Name                Remote Host
*   e5605959c984   default             -
    37726bbf2de2   kurtosis-kloud-01   18.205.223.95
```
```
$ kurtosis context switch kurtosis-kloud-01
INFO[2023-05-08T15:42:58-03:00] Switching context...
INFO[2023-05-08T15:42:58-03:00] Context switched to 'kurtosis-kloud-01', Kurtosis engine will now be restarted
panic: Propagate must be provided with a cause

goroutine 1 [running]:
github.com/kurtosis-tech/stacktrace.Propagate(...)
	/go/pkg/mod/github.com/kurtosis-tech/stacktrace@v0.0.0-20211028211901-1c67a77b5409/stacktrace.go:85
github.com/kurtosis-tech/kurtosis/cli/cli/commands/kurtosis_context/context_switch.run({0x1038b44f0, 0x1400003a0c0}, 0x0?, 0x14000449910?)
	/root/project/cli/cli/commands/kurtosis_context/context_switch/switch.go:118 +0x924
github.com/kurtosis-tech/kurtosis/cli/cli/command_framework/lowlevel.(*LowlevelKurtosisCommand).MustGetCobraCommand.func2(0x140003ffb00?, {0x14000449910, 0x1, 0x1})
	/root/project/cli/cli/command_framework/lowlevel/lowlevel_kurtosis_command.go:294 +0x330
github.com/spf13/cobra.(*Command).execute(0x140003ffb00, {0x140004498d0, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1-0.20230225213037-567ea8ebc9b4/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x10410ae00)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1-0.20230225213037-567ea8ebc9b4/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1-0.20230225213037-567ea8ebc9b4/command.go:992
main.main()
	/root/project/cli/cli/main.go:52 +0x80
```

### Desired behavior

Switching contexts works as expected

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by gbouv** [comment]
The panic is due to this: https://github.com/kurtosis-tech/kurtosis/pull/658.
It's likely that kurtosis somehow encountered some issues restarting the engine after switching context. Unfortunately, because of the panic we will never know why.
With the fix, at least the error will be more user friendly, and next time it happens we will actually know why. 

In the meantime, since I suppose cloud is not at the top of our priorities right now, I'll close that one until we hit this again, unless you disagree
