### ISSUE TITLE
[bug] Kurtosis errors out when running the eth-network-package

### ISSUE THREAD

**Issue by leeederek** [kurtosis-tech/kurtosis#768]
### What's your CLI version?

0.80.0

### Description & steps to reproduce

To replicate, run: `kurtosis run github.com/kurtosis-tech/eth-network-package`

This is the error that I get: 
```bash
panic: Propagate must be provided with a cause

goroutine 1 [running]:
github.com/kurtosis-tech/stacktrace.Propagate(...)
	/go/pkg/mod/github.com/kurtosis-tech/stacktrace@v0.0.0-20211028211901-1c67a77b5409/stacktrace.go:85
github.com/kurtosis-tech/kurtosis/cli/cli/commands.getLatestCLIReleaseVersionFromGitHub()
	/root/project/cli/cli/commands/root.go:309 +0x5b8
github.com/kurtosis-tech/kurtosis/cli/cli/commands.getLatestCLIReleaseVersion()
	/root/project/cli/cli/commands/root.go:253 +0xd8
github.com/kurtosis-tech/kurtosis/cli/cli/commands.isLatestCLIVersion()
	/root/project/cli/cli/commands/root.go:203 +0x20
github.com/kurtosis-tech/kurtosis/cli/cli/commands.checkCLIVersion(0x140001c7d38?)
	/root/project/cli/cli/commands/root.go:186 +0xbc
github.com/kurtosis-tech/kurtosis/cli/cli/commands.globalSetup(0x14000356900?, {0x14000415b70, 0x1, 0x1})
	/root/project/cli/cli/commands/root.go:135 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000356900, {0x14000415b40, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1-0.20230225213037-567ea8ebc9b4/command.go:915 +0x4fc
github.com/spf13/cobra.(*Command).ExecuteC(0x106edc180)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1-0.20230225213037-567ea8ebc9b4/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1-0.20230225213037-567ea8ebc9b4/command.go:992
main.main()
	/root/project/cli/cli/main.go:52 +0x80
```

### Desired behavior

The `eth-network-package` works and I get a local Ethereum node on my machine: https://github.com/kurtosis-tech/eth-network-package

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

**Comment by Peeeekay** [comment]
let me know if this re-occurs; the package is running properly atm.
