### ISSUE TITLE
Kurtosis engine logs - kubernetes - unimplemented panic

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#998]
### What's your CLI version?

0.80.17

### Description & steps to reproduce

`kurtosis engine logs` outputs:
```shell
INFO[2023-07-26T22:56:02+02:00] Engine running in Kubernetes cluster, to connect to the engine from outside the cluster run 'kurtosis gateway' to open a local gateway to the engine
panic: implement me

goroutine 1 [running]:
github.com/kurtosis-tech/kurtosis/container-engine-lib/lib/backend_impls/kubernetes/kubernetes_kurtosis_backend.(*KubernetesKurtosisBackend).GetEngineLogs(0x140006bb9b8?, {0x103455464?, 0x140005b8270?}, {0x140003ee000?, 0x20?})
	/root/project/container-engine-lib/lib/backend_impls/kubernetes/kubernetes_kurtosis_backend/kubernetes_kurtosis_backend.go:41 +0x2c
github.com/kurtosis-tech/kurtosis/container-engine-lib/lib/backend_impls/metrics_reporting.(*MetricsReportingKurtosisBackend).GetEngineLogs(0x1035c2803?, {0x103ea7a60?, 0x140005c8420?}, {0x1400028c3c0, 0x20})
	/root/project/container-engine-lib/lib/backend_impls/metrics_reporting/metrics_reporting_kurtosis_backend.go:89 +0x38
github.com/kurtosis-tech/kurtosis/cli/cli/commands/engine/logs.run({0x103ea7a60, 0x140005c8420}, {0x103ebd2e8, 0x140005d7f90}, {0xe?, 0x10231bc60?}, {0x103ea7a60?, 0x140005c83f0?}, 0x103ab2580?, 0x103e86d78?)
	/root/project/cli/cli/commands/engine/logs/logs.go:65 +0x14c
github.com/kurtosis-tech/kurtosis/cli/cli/command_framework/highlevel/engine_consuming_kurtosis_command.(*EngineConsumingKurtosisCommand).getRunFunc.func1({0x103ea7a60, 0x140005c8420}, 0x0?, 0x104e55cc0?)
	/root/project/cli/cli/command_framework/highlevel/engine_consuming_kurtosis_command/engine_consuming_kurtosis_command.go:233 +0x198
github.com/kurtosis-tech/kurtosis/cli/cli/command_framework/lowlevel.(*LowlevelKurtosisCommand).MustGetCobraCommand.func2(0x14000359b00?, {0x104e55cc0, 0x0, 0x0})
	/root/project/cli/cli/command_framework/lowlevel/lowlevel_kurtosis_command.go:294 +0x330
github.com/spf13/cobra.(*Command).execute(0x14000359b00, {0x104e55cc0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x104e05260)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/root/project/cli/cli/main.go:52 +0x80
```

Note: the `kurtosis gateway` command is running in another terminal. And I have one enclave running on kubernetes cluster.

### Desired behavior

Show the actual engine logs.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by leoporoli** [comment]
@barnabasbusa this issue was fixed, you have to upgrade Kurtosis to version `0.80.22` and you will be able to use this command with the Kubernetes cluster
